repository:
  name: francois.dautreme.fr
  description: My personal website
  homepage: https://francois.dautreme.fr/
  topics: website, francois, dautreme.fr
  private: true

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: article
    color: "#E8CD3A"
    description: Article request

  - name: turorial
    color: "#0E8A16"
    description: Turorial request

  - name: typos
    color: "#D93F0B"
    description: Fix typos

  - name: bug
    color: "#B60205"
    description: Something is not working

branches:
  - name: main
